#!/bin/bash
# note: you need to change the file name to "Makefile"
prog: main.o binary_tree.o binary_search_tree.o
		gcc -o prog main.o binary_tree.o binary_search_tree.o
main.o: main.c binary_tree.h binary_search_tree.h
		gcc -c main.c -o main.o -std=c99
binary_tree.o: binary_tree.c binary_tree.h
		gcc -c binary_tree.c -o binary_tree.o -std=c99
binary_search_tree.o: binary_search_tree.c binary_search_tree.h
		gcc -c binary_search_tree.c -o binary_search_tree.o -std=c99

.PHONY: clean
clean:
		rm *.o
		rm prog
