#!/bin/bash
# note: you need to change the file name to "Makefile"
CC ?= gcc
CFLAGS ?= -c -Wall -g
CSTD ?=c99
prog: main.o binary_tree.o binary_search_tree.o
		$(CC) -o prog main.o binary_tree.o binary_search_tree.o
main.o: main.c binary_tree.h binary_search_tree.h
		$(CC) -o main.o $(CFLAGS) main.c -std=$(CSTD)
binary_tree.o: binary_tree.c binary_tree.h
		$(CC) -o binary_tree.o $(CFLAGS) binary_tree.c -std=$(CSTD)
binary_search_tree.o: binary_search_tree.c binary_search_tree.h
		$(CC) -o binary_search_tree.o $(CFLAGS) binary_search_tree.c -std=$(CSTD)

.PHONY: clean
clean:
		rm *.o
		rm prog
